name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - TAG: linux-x64
          - TAG: linux-arm
          - TAG: win-x86

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet publish -r ${{ matrix.TAG }} -p:PublishSingleFile=true -c Release -nowarn:CS8632,CS0168,CS0162,CS1998
    - name: Upload Build Result
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.TAG }}
        path: ./ProjectEarthLauncher/bin/Release/net5.0/${{ matrix.TAG }}/publish
